name: Build

on: [push, pull_request]

jobs:
  build_mingw_lite:
    name: Build with mingw-lite
    strategy:
      fail-fast: false
      matrix:
        profile: [
          64-mcf, 64-ucrt, 64-msvcrt,
          32-mcf, 32-ucrt, 32-msvcrt,
        ]
        os: [ubuntu-24.04, windows-2022]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Build (cross)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo .ci/build-cross.sh -p ${{ matrix.profile }}

      - name: Build (native)
        if: matrix.os == 'windows-2022'
        run: |
          .ci/build-native.sh -p ${{ matrix.profile }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Qt with mingw-lite ${{ matrix.profile }} (${{ matrix.os }})
          path: build/*.tar.zst

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.tar.zst

  build_mingw_builds:
    name: Build with mingw-builds
    strategy:
      fail-fast: false
      matrix:
        profile: [64, 32]
        mode: [release, debug]
    runs-on: windows-2022
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          .ci/build-native.sh --use-mingw-builds -p ${{ matrix.profile }} $( [[ "${{ matrix.mode }}" == debug ]] && echo -n --debug )

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Qt with mingw-builds ${{ matrix.profile }} ${{ matrix.mode }}
          path: build/*.tar.zst

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.tar.zst
